apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque

# Note that secrets aren't secured: `echo secret_generated | base64 -d`
stringData:
  accessKey: "SAMPLE_ACCESS_KEY_1234567890"
  secretKey: "SECRET_KEY_123456"