# Local Storage - mongo-pvc
# What do I want
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  resources:
    requests:
      storage: 8Gi # Find 8-gigabytes of starage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
# How I want it implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  hostPath:
    path: "/mnt/some_new/directorystructure"
    type: DirectoryOrCreate

  capacity:
    storage: 8Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # Supported by AWS
  # persistentVolumeReclaimPolicy: Recycle
  # storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
