apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
  labels:
    app: queue
    
spec:
  # modify replicas according to demand/desire
  replicas: 1
  # minReadySeconds: 30 # This ensures a particular microservice is always available
  
  selector:
    matchLabels:
      app: queue

  template: # template for the pods
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
  labels:
    app: position-simulator
    
spec:
  # modify replicas according to demand/desire
  replicas: 1
  # minReadySeconds: 30 # This ensures a particular microservice is always available
  
  selector:
    matchLabels:
      app: position-simulator

  template: # template for the pods
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
      - name: position-simulator
        image: richardchesterwood/k8s-fleetman-position-simulator:release1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
  labels:
    app: position-tracker
    
spec:
  # modify replicas according to demand/desire
  replicas: 1
  # minReadySeconds: 30 # This ensures a particular microservice is always available
  
  selector:
    matchLabels:
      app: position-tracker

  template: # template for the pods
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
      - name: position-tracker
        image: richardchesterwood/k8s-fleetman-position-tracker:release1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    
spec:
  # modify replicas according to demand/desire
  replicas: 1
  # minReadySeconds: 30 # This ensures a particular microservice is always available
  
  selector:
    matchLabels:
      app: api-gateway

  template: # template for the pods
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: richardchesterwood/k8s-fleetman-api-gateway:release1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice