apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
  labels:
    app: queue
    
spec:
  # modify replicas according to demand/desire
  replicas: 1
  # minReadySeconds: 30 # This ensures a particular microservice is always available
  
  selector:
    matchLabels:
      app: queue

  template: # template for the pods
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-queue:release1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
  labels:
    app: position-simulator
    
spec:
  # modify replicas according to demand/desire
  replicas: 1
  # minReadySeconds: 30 # This ensures a particular microservice is always available
  
  selector:
    matchLabels:
      app: position-simulator

  template: # template for the pods
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-position-simulator:release1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice