# kubectl autoscale deployment api-getway --cpu-percent 400 --min 1 --max 4
# kubectl get hpa
# kubectl top pod
# kubectl decsribe hpa api-gateway
# kubectl get hp api-gateway -o yaml # this will generate the yaml format of the autoscaler

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 400

