apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque

# Note that secrets aren't secured: `echo secret_generated | base64 -d`
stringData:
  accessKey: "SAMPLE_ACCESS_KEY_1234567890"
  secretKey: "SECRET_KEY_123456"

---

# Securing ActiveMQ from public using the auth file: HTTPS Required
# htpasswd -c auth 'enter-password': this will create a file call auth
# RUN: 
#     `kubectl create secret generic mycredentials --from-file auth`
#     `kubectl get secret mycredentials`
#     `kubectl get secret mycredentials -o yaml` This will output the yaml context
apiVersion: v1
data:
  auth: YWRtaW46JGFwcjEkR29VMTJnSi4kSlRnSVNrTzRJdUtaeXh4UWhhVTdOLwo=
kind: Secret
metadata:
  creationTimestamp: "2023-07-21T11:38:57Z"
  name: mycredentials
  namespace: default
  resourceVersion: "2474"
  uid: ab7e0be6-7416-4d56-a0d1-04861fb32fe6
type: Opaque