# Local Storage - mongo-pvc
# What do I want
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: cloud-ssd #mylocalstorage # What type of storage I want
  resources:
    requests:
      storage: 8Gi # Find 8-gigabytes of starage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
# How I want it implemented
# Local Storage

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-storage
# spec:
#   storageClassName: mylocalstorage
#   hostPath:
#     path: "/mnt/some_new/directorystructure"
#     type: DirectoryOrCreate

#   capacity:
    # storage: 8Gi
  # volumeMode: Filesystem
  # accessModes:
    # - ReadWriteOnce # Supported by AWS
  # persistentVolumeReclaimPolicy: Recycle
  # storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2


apiVersion: storage.k8.io/vi
kind: storageClass
metadata:
  name: cloud-ssd
provisioner: kubernetes.io/aws-abs
parameters:
  type: gp2 # I could choose the Zone but will let the cluster choose it's Zone
# reclaimPolicy: Retain # Delete
# allowVolumeExpansion: true
# mountOptions:
#   - debug
# volumeBindingMode: Immediate