apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-sample
spec:
  schedule: "* * * * *" # "minute hour day month day"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
      backoffLimit: 2